<h2 style="color:blue; font-size:28px;">
Building machine learning models
</h2>

In [2]:
import pandas as pd
df = pd.read_excel("C:\\Users\\LENOVO\\Documents\\candy distribution sales.xlsx")
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Country/Region,City,State/Province,Postal_Code,Division,Region,Product_ID,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912

In [35]:
x = df[['Ship_Mode', 'Division', 'Region', 'Product_Name', 'Sales', 'Units', 'Gross_Profit', 'Cost', 'Shipping_Days']]
x.head(2)

,Ship_Mode,Division,Region,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,Standard Class,Chocolate,Interior,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,909
1,Standard Class,Chocolate,Interior,Wonka Bar - Triple Dazzle Caramel,7.5,2,4.90,2.60,909

In [6]:
x_new = x.copy()
x_new.head()

,Ship_Mode,Division,Region,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,Standard Class,Chocolate,Interior,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909
1,Standard Class,Chocolate,Interior,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909
2,Standard Class,Chocolate,Interior,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909
3,Standard Class,Chocolate,Interior,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909
4,Standard Class,Chocolate,Atlantic,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912

In [24]:
x_new['Shipping_Days'].unique()

array([0.00677507, 0.01084011, 0.00271003, 0.00406504, 0.00813008,
       0.00542005, 0.00948509, 0.00135501, 0.        , 0.01490515,
       0.50542005, 0.49864499, 0.50271003, 0.50406504, 0.50135501,
       0.5       , 0.49728997, 0.49593496, 0.49457995, 0.99457995,
       0.99593496, 0.99051491, 0.99186992, 0.99864499, 0.99728997,
       0.99322493, 0.98915989, 1.        ])

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_new['Ship_Mode'] = le.fit_transform(x_new['Ship_Mode'])
x_new['Division'] = le.fit_transform(x_new['Division'])
x_new['Region'] = le.fit_transform(x_new['Region'])
x_new['Product_Name'] = le.fit_transform(x_new['Product_Name'])
x_new.head(2)

,Ship_Mode,Division,Region,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,3,0,2,9,6.5,2,4.22,2.28,909
1,3,0,2,11,7.5,2,4.90,2.60,909

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_new['Shipping_Days'] = scaler.fit_transform(x_new[['Shipping_Days']])
x_new.head(2)

,Ship_Mode,Division,Region,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,3,0,2,9,6.5,2,4.22,2.28,0.006775
1,3,0,2,11,7.5,2,4.90,2.60,0.006775

In [37]:
x_new.head(1)

,Ship_Mode,Division,Region,Product_Name,Sales,Units,Gross_Profit,Cost,Shipping_Days
0,3,0,2,9,6.5,2,4.22,2.28,0.006775

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

a = x_new[['Ship_Mode',	'Division',	'Region', 'Product_Name', 'Units', 'Shipping_Days']]
b = x_new[['Sales', 'Gross_Profit', 'Cost']]

a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

model1 = LinearRegression()
model1.fit(a_train, b_train)

model2 = DecisionTreeRegressor()
model2.fit(a_train, b_train)

model3 = RandomForestRegressor()
model3.fit(a_train, b_train)

model4 = KNeighborsRegressor()
model4.fit(a_train, b_train)

b_pre = model2.predict(a_test)


print("Mean Squared Error =", mean_squared_error(b_test, b_pre))
print("Mean Absolute Error =", mean_absolute_error(b_test, b_pre))
print("R² Score =", r2_score(b_test, b_pre))

Mean Squared Error = 0.09160839353285173
Mean Absolute Error = 0.007478500172008694
R² Score = 0.9948423791283267

In [46]:
c = float(input("Enter ship mode:"))
d = float(input("Enter division:"))
e = float(input("Enter Region:"))
f = float(input("Enter product name:"))
g = float(input("Enter Units :"))
h = float(input("Enter Shipping_Days:"))

prediction = model2.predict([[c, d, e, f, g, h])

print(prediction)

Enter ship mode: 3
Enter division: 0
Enter Region: 2
Enter product name: 9
Enter Units : 2
Enter Shipping_Days: 0.0067

[[6.5  4.22 2.28]]

C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(